services:
  db:
    image: postgres:13
    restart: no
    environment:
      POSTGRES_DB: recipe_shopper
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  