import { Box, Flex } from '@chakra-ui/react';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import ApolloChakraProvider from './ApolloChakraProvider';
import Sidebar from './components/Sidebar';
import { SessionProvider } from 'next-auth/react';
import Header from './components/header';
import NextAuthProvider from '@/src/providers/NextAuth';
import { MobileMenu } from './components/layout/MobileMenu';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <NextAuthProvider>
          <ApolloChakraProvider>
            <SessionProvider>
              <Flex
                h="100vh"
                w="100%"
                bgColor="orange.100"
                alignItems="stretch"
                gap={4}
                p={{ base: 2, md: 4 }}
              >
                <Box display={{ base: 'none', md: 'block' }} flexShrink={0}>
                  <Sidebar />
                </Box>
                <Flex flexDirection="column" flex={1} gap={4} minW={0}>
                  <Box
                    h={{ base: '50px', md: '60px' }}
                    bgColor="orange.50"
                    borderRadius={10}
                    display="flex"
                    alignItems="center"
                    px={4}
                    justifyContent="space-between"
                  >
                    <MobileMenu />
                    <Header />
                  </Box>
                  <Box
                    flex={1}
                    bgColor="orange.50"
                    borderRadius={10}
                    p={4}
                    overflowY="auto"
                    minH={0}
                  >
                    {children}
                  </Box>
                </Flex>
              </Flex>
            </SessionProvider>
          </ApolloChakraProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
